### ISSUE TITLE
Package not on packagist

### ISSUE THREAD

**Issue by admench** [pixelandtonic/RedactorClips#12]
Hey,

Searching or trying to install this package doesn't work:

https://packagist.org/search/?q=craftcms%2Fredactor-clips

```
Composer
[InvalidArgumentException]
Could not find a matching version of package craftcms/redactor-clips.
```

**Comment by admench** [comment]
Bump - @angrybrad is there any chance you could get this up on packagist please? Thanks

**Comment by angrybrad** [comment]
@admench probably be next week before we can get to to it. Big launch day tomorrow.

**Comment by admench** [comment]
Any way this can be sorted out please? Thank you

**Comment by admench** [comment]
Many thanks @angrybrad 👍🏼
